version: "3.2"

services:
  db-server:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
        - ./db-server/init.sql:/docker-entrypoint-initdb.d/custom-init.sql
  redis-server:
    image: redis:latest
  rabbitmq-server:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}

  auth-server:
    build: auth-server/
    depends_on:
      - db-server
      - redis-server
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
  resize-server:
    build: resize-server/
    environment:
      - UPLOADING_PATH=/images
      - RABBITMQ_CHANNEL=${RABBITMQ_CHANNEL}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - ./resize-server/app:/app
      - ./images:/images
    depends_on:
      - rabbitmq-server
      - auth-server
  resize-worker:
    build: resize-worker/
    environment:
      - UPLOADING_PATH=/images
      - RABBITMQ_CHANNEL=${RABBITMQ_CHANNEL}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - ./images:/images
    depends_on:
      - rabbitmq-server
      - resize-server
  frontend-server:
    build: frontend-server/
    depends_on:
      - auth-server
      - resize-server
    volumes:
      - ./frontend-server/source:/var/www
    ports:
      - '80:80'
