version: "3.2"

services:
  db-server:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
        - ./db-server/init.sql:/docker-entrypoint-initdb.d/custom-init.sql
  redis-server:
    image: redis:latest
  auth-server:
    build: auth-server/
    depends_on:
      - db-server
      - redis-server
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
  frontend-server:
    build: frontend-server/
    depends_on:
      - auth-server
    volumes:
      - ./frontend-server/source:/var/www
    ports:
      - '80:80'
